include:
  - project: "mmc-ch/mimacom-development/ci-templates"
    file: "/templates/kaniko.gitlab-ci.yml"
    ref: "v8.1"
  - project: "mmc-ch/mimacom-development/ci-templates"
    file: "/templates/kubectl.gitlab-ci.yml"
    ref: "v8.1"
  - project: "mmc-ch/mimacom-development/ci-templates"
    file: "/templates/node.gitlab-ci.yml"
    ref: "v8.1"
  - local: ".gitlab/ci/.build.yml"

variables:
  VERSION: "1.0"

stages:
  - build
  - test
  - deploy
