fe:build:
  stage: build
  extends:
    - .npm-ci
  variables:
    NPM_CONTEXT_DIR: .
  after_script:
    - npm run build
  artifacts:
    paths:
      - apps/backend/build
      - apps/frontend/dist
